name: Classes
main: io.github.com.revenantgaze.classes.Main
version: 1.0.4.5
author: RevenantGaze
commands:
  class:
    description: Check which class you are a part of!
    usage: /class
    default: true
    permission: classes.command.class
permissions:
  classes.*:
    description: Gives the player all Classes permissions!
    children: 
      classes.sign.create: true
      classes.sign.use: true
      classes.command.class: true
  classes.sign.create:
    description: Makes the player able to create Classes signs!
    default: op
  classes.sign.use:
    description: Makes the player able to use Classes signs!
    default: op
  classes.command.class:
    description: Allows the player to check the class he/she is a part of!
    default: true